---
debug: false
service_port: 7004
service_host: 0.0.0.0
es_host: localhost
es_port: 9200
es_index: reports_vertebrates
ens_version: 110
eg_version: 57
dc_uri: http://localhost:5000/api/vertebrates/datachecks/

dispatch_targets:
 core: 'localhost'

retry_wait: 30
celery_broker_url: "pyamqp://localhost:31772/production"
result_backend: "rpc://localhost:31772/production"
dispatch_all: true
dispatch_target:
 core: mysql://ensembl@localhost:3306
